# Generated by Django 4.1.4 on 2022-12-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_website', '0002_donate'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='date_donated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
